In [1]:
import numpy as np

In [25]:
#1 Write a Python Program to Add Two Matrices?
def add_matrix(a,b):
    return a+b
np.random.seed(1)
a=np.matrix(np.random.randint(5,10,(3,3)))
b=np.matrix(np.random.randint(5,10,(3,3)))
add_matrix(a,b)

matrix([[17, 15, 12],
        [15, 15, 14],
        [13, 15, 16]])

In [37]:
#2 Write a Python Program to Multiply Two Matrices?

a=np.array([[5,8,9],[7,2,6],[4,6,8]])
b=np.array([[8,4,7],[2,6,4],[7,1,12]])
a@b

array([[119,  77, 175],
       [102,  46, 129],
       [100,  60, 148]])

In [38]:
#3 Write a Python Program to Transpose a Matrix?
a=np.array([[5,8,9],[7,2,6],[4,6,8]])
a.T

array([[5, 7, 4],
       [8, 2, 6],
       [9, 6, 8]])

In [56]:
#4 Write a Python Program to Sort Words in Alphabetic Order?
a='hi i am learning python'
b=list(a.split(" "))
sorted(b)

['am', 'hi', 'i', 'learning', 'python']

In [61]:
#5 Write a Python Program to Remove Punctuation From a String?
import string
def pun(value):
    a = ""
    for i in value:
        if i not in string.punctuation:
            a += i
    return a
b = "H&@*i@ &#(I&@(a&*M)@* $S*&T*(u@&D)Y*(#I*@(N&(g(&@ &P)&%%@y%^@T^*%h^#^O^@N"
print(pun(b))

Hi IaM STuDYINg PyThON
